<a href="https://colab.research.google.com/github/dralmadani/learning/blob/main/pruning/pruning_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
%matplotlib inline


# Pruning Tutorial
**Author**: [Michela Paganini](https://github.com/mickypaganini)

State-of-the-art deep learning techniques rely on over-parametrized models 
that are hard to deploy. On the contrary, biological neural networks are 
known to use efficient sparse connectivity. Identifying optimal  
techniques to compress models by reducing the number of parameters in them is 
important in order to reduce memory, battery, and hardware consumption without 
sacrificing accuracy. This in turn allows you to deploy lightweight models on device, and guarantee 
privacy with private on-device computation. On the research front, pruning is 
used to investigate the differences in learning dynamics between 
over-parametrized and under-parametrized networks, to study the role of lucky 
sparse subnetworks and initializations
("[lottery tickets](https://arxiv.org/abs/1803.03635)") as a destructive 
neural architecture search technique, and more.

In this tutorial, you will learn how to use ``torch.nn.utils.prune`` to 
sparsify your neural networks, and how to extend it to implement your 
own custom pruning technique.

## Requirements
``"torch>=1.4.0a0+8e8a5e0"``


In [87]:
import torch
from torch import nn
import torch.nn.utils.prune as prune
import torch.nn.functional as F

## Create a model

In this tutorial, we use the [LeNet](http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf) architecture from 
LeCun et al., 1998.



In [88]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square conv kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5x5 image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, int(x.nelement() / x.shape[0]))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

model = LeNet().to(device=device)

## Inspect a Module

Let's inspect the (unpruned) ``conv1`` layer in our LeNet model. It will contain two 
parameters ``weight`` and ``bias``, and no buffers, for now.



In [89]:
print(model)


LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [90]:
# print(vgg)
# summary(vgg, (3, 32, 32))


In [91]:
from torchvision import models
from torchsummary import summary


# vgg = models.vgg16()
# summary(vgg, input_size , batch_size=-1, device='cpu')
# summary(model, input_size, batch_size=-1, device='cuda')
# summary(model, input_size = ( 6,6), batch_size=-1, device='cuda')

In [92]:
# vgg_module = model.conv1
# print(list(vgg_module.named_parameters()))

In [93]:
module = model.conv1
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[-0.2045, -0.0369, -0.0503],
          [-0.0531, -0.2477, -0.0336],
          [ 0.3263, -0.2546, -0.2760]]],


        [[[ 0.1915, -0.1756, -0.0692],
          [ 0.2582,  0.2328,  0.1070],
          [-0.1093,  0.2669, -0.0078]]],


        [[[-0.1390, -0.1930, -0.1108],
          [ 0.1681,  0.0749, -0.3172],
          [-0.1882,  0.3161, -0.1487]]],


        [[[-0.2394, -0.0184,  0.1541],
          [-0.0269,  0.1347,  0.1992],
          [ 0.1289,  0.2432,  0.1158]]],


        [[[-0.1959, -0.2725,  0.0892],
          [ 0.0199,  0.0589, -0.1596],
          [ 0.3321, -0.1879, -0.1992]]],


        [[[-0.1161, -0.1167, -0.2128],
          [-0.0802, -0.0093,  0.1980],
          [-0.1367,  0.3285,  0.2166]]]], requires_grad=True)), ('bias', Parameter containing:
tensor([-0.2080, -0.0636, -0.2399,  0.0928,  0.2952, -0.0242],
       requires_grad=True))]


In [94]:
print(list(module.named_buffers()))

[]


In [101]:
print(module.weight)
print ('*'* 20)
print(module.bias)

Parameter containing:
tensor([[[[-0.2045, -0.0369, -0.0503],
          [-0.0531, -0.2477, -0.0336],
          [ 0.3263, -0.2546, -0.2760]]],


        [[[ 0.1915, -0.1756, -0.0692],
          [ 0.2582,  0.2328,  0.1070],
          [-0.1093,  0.2669, -0.0078]]],


        [[[-0.1390, -0.1930, -0.1108],
          [ 0.1681,  0.0749, -0.3172],
          [-0.1882,  0.3161, -0.1487]]],


        [[[-0.2394, -0.0184,  0.1541],
          [-0.0269,  0.1347,  0.1992],
          [ 0.1289,  0.2432,  0.1158]]],


        [[[-0.1959, -0.2725,  0.0892],
          [ 0.0199,  0.0589, -0.1596],
          [ 0.3321, -0.1879, -0.1992]]],


        [[[-0.1161, -0.1167, -0.2128],
          [-0.0802, -0.0093,  0.1980],
          [-0.1367,  0.3285,  0.2166]]]], requires_grad=True)
********************
Parameter containing:
tensor([-0.2080, -0.0636, -0.2399,  0.0928,  0.2952, -0.0242],
       requires_grad=True)


## Pruning a Module

To prune a module (in this example, the ``conv1`` layer of our LeNet 
architecture), first select a pruning technique among those available in 
``torch.nn.utils.prune`` (or
[implement](#extending-torch-nn-utils-pruning-with-custom-pruning-functions)
your own by subclassing 
``BasePruningMethod``). Then, specify the module and the name of the parameter to 
prune within that module. Finally, using the adequate keyword arguments 
required by the selected pruning technique, specify the pruning parameters.

In this example, we will prune at random 30% of the connections in 
the parameter named ``weight`` in the ``conv1`` layer.
The module is passed as the first argument to the function; ``name`` 
identifies the parameter within that module using its string identifier; and 
``amount`` indicates either the percentage of connections to prune (if it 
is a float between 0. and 1.), or the absolute number of connections to 
prune (if it is a non-negative integer).



In [9]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

Pruning acts by removing ``weight`` from the parameters and replacing it with 
a new parameter called ``weight_orig`` (i.e. appending ``"_orig"`` to the 
initial parameter ``name``). ``weight_orig`` stores the unpruned version of 
the tensor. The ``bias`` was not pruned, so it will remain intact.



In [10]:
print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([ 0.2546, -0.2674,  0.2974, -0.0682, -0.2642,  0.2121],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 0.1496, -0.3023, -0.2438],
          [ 0.2126, -0.1133,  0.1834],
          [ 0.1078, -0.1044,  0.2714]]],


        [[[-0.3030,  0.1866,  0.0981],
          [ 0.1191, -0.0111,  0.0293],
          [ 0.1350,  0.2438,  0.3189]]],


        [[[ 0.2405, -0.2004, -0.2549],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0078,  0.0792,  0.2938]]],


        [[[-0.0651,  0.1800,  0.0074],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.2859,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.2472],
          [-0.2792, -0.2536, -0.0531]]],


        [[[ 0.1682,  0.1154, -0.1251],
          [-0.1167,  0.1291, -0.2735],
          [ 0.0724, -0.0380,  0.0469]]]], requires_grad=True))]


The pruning mask generated by the pruning technique selected above is saved 
as a module buffer named ``weight_mask`` (i.e. appending ``"_mask"`` to the 
initial parameter ``name``).



In [11]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 0., 1.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 0., 1.],
          [0., 1., 1.],
          [0., 0., 1.]]],


        [[[1., 1., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [1., 1., 1.],
          [1., 0., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 1.],
          [1., 0., 0.]]]]))]


For the forward pass to work without modification, the ``weight`` attribute 
needs to exist. The pruning techniques implemented in 
``torch.nn.utils.prune`` compute the pruned version of the weight (by 
combining the mask with the original parameter) and store them in the 
attribute ``weight``. Note, this is no longer a parameter of the ``module``,
it is now simply an attribute.



In [12]:

print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([ 0.2546, -0.2674,  0.2974, -0.0682, -0.2642,  0.2121],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 0.1496, -0.3023, -0.2438],
          [ 0.2126, -0.1133,  0.1834],
          [ 0.1078, -0.1044,  0.2714]]],


        [[[-0.3030,  0.1866,  0.0981],
          [ 0.1191, -0.0111,  0.0293],
          [ 0.1350,  0.2438,  0.3189]]],


        [[[ 0.2405, -0.2004, -0.2549],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0078,  0.0792,  0.2938]]],


        [[[-0.0651,  0.1800,  0.0074],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.2859,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.2472],
          [-0.2792, -0.2536, -0.0531]]],


        [[[ 0.1682,  0.1154, -0.1251],
          [-0.1167,  0.1291, -0.2735],
          [ 0.0724, -0.0380,  0.0469]]]], requires_grad=True))]


In [13]:
print(module.weight)

tensor([[[[ 0.1496, -0.0000, -0.2438],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000]]],


        [[[-0.3030,  0.0000,  0.0981],
          [ 0.0000, -0.0111,  0.0293],
          [ 0.0000,  0.0000,  0.3189]]],


        [[[ 0.2405, -0.2004, -0.0000],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0000,  0.0000,  0.0000],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.0000,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.0000],
          [-0.2792, -0.0000, -0.0000]]],


        [[[ 0.1682,  0.0000, -0.0000],
          [-0.0000,  0.1291, -0.2735],
          [ 0.0724, -0.0000,  0.0000]]]], grad_fn=<MulBackward0>)


Finally, pruning is applied prior to each forward pass using PyTorch's
``forward_pre_hooks``. Specifically, when the ``module`` is pruned, as we 
have done here, it will acquire a ``forward_pre_hook`` for each parameter 
associated with it that gets pruned. In this case, since we have so far 
only pruned the original parameter named ``weight``, only one hook will be
present.



In [14]:
print(module._forward_pre_hooks)

OrderedDict([(1, <torch.nn.utils.prune.PruningContainer object at 0x7f364423ba00>)])


For completeness, we can now prune the ``bias`` too, to see how the 
parameters, buffers, hooks, and attributes of the ``module`` change.
Just for the sake of trying out another pruning technique, here we prune the 
3 smallest entries in the bias by L1 norm, as implemented in the 
``l1_unstructured`` pruning function.



In [15]:
prune.l1_unstructured(module, name="bias", amount=3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

We now expect the named parameters to include both ``weight_orig`` (from 
before) and ``bias_orig``. The buffers will include ``weight_mask`` and 
``bias_mask``. The pruned versions of the two tensors will exist as 
module attributes, and the module will now have two ``forward_pre_hooks``.



In [16]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.1496, -0.3023, -0.2438],
          [ 0.2126, -0.1133,  0.1834],
          [ 0.1078, -0.1044,  0.2714]]],


        [[[-0.3030,  0.1866,  0.0981],
          [ 0.1191, -0.0111,  0.0293],
          [ 0.1350,  0.2438,  0.3189]]],


        [[[ 0.2405, -0.2004, -0.2549],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0078,  0.0792,  0.2938]]],


        [[[-0.0651,  0.1800,  0.0074],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.2859,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.2472],
          [-0.2792, -0.2536, -0.0531]]],


        [[[ 0.1682,  0.1154, -0.1251],
          [-0.1167,  0.1291, -0.2735],
          [ 0.0724, -0.0380,  0.0469]]]], requires_grad=True)), ('bias_orig', Parameter containing:
tensor([ 0.2546, -0.2674,  0.2974, -0.0682, -0.2642,  0.2121],
       requires_grad=True))]


In [17]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 0., 1.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 0., 1.],
          [0., 1., 1.],
          [0., 0., 1.]]],


        [[[1., 1., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [1., 1., 1.],
          [1., 0., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 1.],
          [1., 0., 0.]]]])), ('bias_mask', tensor([0., 1., 1., 0., 1., 0.]))]


In [18]:
print(module.bias)

tensor([ 0.0000, -0.2674,  0.2974, -0.0000, -0.2642,  0.0000],
       grad_fn=<MulBackward0>)


In [19]:
print(module._forward_pre_hooks)

OrderedDict([(1, <torch.nn.utils.prune.PruningContainer object at 0x7f364423ba00>), (2, <torch.nn.utils.prune.L1Unstructured object at 0x7f364423b5e0>)])


## Iterative Pruning

The same parameter in a module can be pruned multiple times, with the 
effect of the various pruning calls being equal to the combination of the
various masks applied in series.
The combination of a new mask with the old mask is handled by the 
``PruningContainer``'s ``compute_mask`` method.

Say, for example, that we now want to further prune ``module.weight``, this
time using structured pruning along the 0th axis of the tensor (the 0th axis 
corresponds to the output channels of the convolutional layer and has 
dimensionality 6 for ``conv1``), based on the channels' L2 norm. This can be 
achieved using the ``ln_structured`` function, with ``n=2`` and ``dim=0``.



In [20]:
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

# As we can verify, this will zero out all the connections corresponding to 
# 50% (3 out of 6) of the channels, while preserving the action of the 
# previous mask.
print(module.weight)

tensor([[[[ 0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000]]],


        [[[-0.0000,  0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[ 0.2405, -0.2004, -0.0000],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0000,  0.0000,  0.0000],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.0000,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.0000],
          [-0.2792, -0.0000, -0.0000]]],


        [[[ 0.0000,  0.0000, -0.0000],
          [-0.0000,  0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000]]]], grad_fn=<MulBackward0>)


The corresponding hook will now be of type 
``torch.nn.utils.prune.PruningContainer``, and will store the history of 
pruning applied to the ``weight`` parameter.



In [21]:
for hook in module._forward_pre_hooks.values():
    if hook._tensor_name == "weight":  # select out the correct hook
        break

print(list(hook))  # pruning history in the container

[<torch.nn.utils.prune.RandomUnstructured object at 0x7f364423b490>, <torch.nn.utils.prune.RandomUnstructured object at 0x7f364423b880>, <torch.nn.utils.prune.LnStructured object at 0x7f364423b310>]


## Serializing a pruned model
All relevant tensors, including the mask buffers and the original parameters
used to compute the pruned tensors are stored in the model's ``state_dict`` 
and can therefore be easily serialized and saved, if needed.



In [22]:
print(model.state_dict().keys())

odict_keys(['conv1.weight_orig', 'conv1.bias_orig', 'conv1.weight_mask', 'conv1.bias_mask', 'conv2.weight', 'conv2.bias', 'fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias'])


## Remove pruning re-parametrization

To make the pruning permanent, remove the re-parametrization in terms
of ``weight_orig`` and ``weight_mask``, and remove the ``forward_pre_hook``,
we can use the ``remove`` functionality from ``torch.nn.utils.prune``.
Note that this doesn't undo the pruning, as if it never happened. It simply 
makes it permanent, instead, by reassigning the parameter ``weight`` to the 
model parameters, in its pruned version.



Prior to removing the re-parametrization:



In [23]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.1496, -0.3023, -0.2438],
          [ 0.2126, -0.1133,  0.1834],
          [ 0.1078, -0.1044,  0.2714]]],


        [[[-0.3030,  0.1866,  0.0981],
          [ 0.1191, -0.0111,  0.0293],
          [ 0.1350,  0.2438,  0.3189]]],


        [[[ 0.2405, -0.2004, -0.2549],
          [-0.1561, -0.2141, -0.2966],
          [ 0.0078,  0.0792,  0.2938]]],


        [[[-0.0651,  0.1800,  0.0074],
          [ 0.1169, -0.1011,  0.3257],
          [-0.0018,  0.2859,  0.3029]]],


        [[[ 0.0280,  0.1943,  0.2227],
          [ 0.2977,  0.1650,  0.2472],
          [-0.2792, -0.2536, -0.0531]]],


        [[[ 0.1682,  0.1154, -0.1251],
          [-0.1167,  0.1291, -0.2735],
          [ 0.0724, -0.0380,  0.0469]]]], requires_grad=True)), ('bias_orig', Parameter containing:
tensor([ 0.2546, -0.2674,  0.2974, -0.0682, -0.2642,  0.2121],
       requires_grad=True))]


In [ ]:
print(list(module.named_buffers()))

In [ ]:
print(module.weight)

After removing the re-parametrization:



In [ ]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

In [ ]:
print(list(module.named_buffers()))

## Pruning multiple parameters in a model 

By specifying the desired pruning technique and parameters, we can easily 
prune multiple tensors in a network, perhaps according to their type, as we 
will see in this example.



In [ ]:
new_model = LeNet()
for name, module in new_model.named_modules():
    # prune 20% of connections in all 2D-conv layers 
    if isinstance(module, torch.nn.Conv2d):
        prune.l1_unstructured(module, name='weight', amount=0.2)
    # prune 40% of connections in all linear layers 
    elif isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.4)

print(dict(new_model.named_buffers()).keys())  # to verify that all masks exist

## Global pruning

So far, we only looked at what is usually referred to as "local" pruning,
i.e. the practice of pruning tensors in a model one by one, by 
comparing the statistics (weight magnitude, activation, gradient, etc.) of 
each entry exclusively to the other entries in that tensor. However, a 
common and perhaps more powerful technique is to prune the model all at 
once, by removing (for example) the lowest 20% of connections across the 
whole model, instead of removing the lowest 20% of connections in each 
layer. This is likely to result in different pruning percentages per layer.
Let's see how to do that using ``global_unstructured`` from 
``torch.nn.utils.prune``.



In [ ]:
model = LeNet()

parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.conv2, 'weight'),
    (model.fc1, 'weight'),
    (model.fc2, 'weight'),
    (model.fc3, 'weight'),
)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

Now we can check the sparsity induced in every pruned parameter, which will 
not be equal to 20% in each layer. However, the global sparsity will be 
(approximately) 20%.



In [ ]:
print(
    "Sparsity in conv1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv1.weight == 0))
        / float(model.conv1.weight.nelement())
    )
)
print(
    "Sparsity in conv2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv2.weight == 0))
        / float(model.conv2.weight.nelement())
    )
)
print(
    "Sparsity in fc1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc1.weight == 0))
        / float(model.fc1.weight.nelement())
    )
)
print(
    "Sparsity in fc2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc2.weight == 0))
        / float(model.fc2.weight.nelement())
    )
)
print(
    "Sparsity in fc3.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc3.weight == 0))
        / float(model.fc3.weight.nelement())
    )
)
print(
    "Global sparsity: {:.2f}%".format(
        100. * float(
            torch.sum(model.conv1.weight == 0)
            + torch.sum(model.conv2.weight == 0)
            + torch.sum(model.fc1.weight == 0)
            + torch.sum(model.fc2.weight == 0)
            + torch.sum(model.fc3.weight == 0)
        )
        / float(
            model.conv1.weight.nelement()
            + model.conv2.weight.nelement()
            + model.fc1.weight.nelement()
            + model.fc2.weight.nelement()
            + model.fc3.weight.nelement()
        )
    )
)

## Extending ``torch.nn.utils.prune`` with custom pruning functions
To implement your own pruning function, you can extend the
``nn.utils.prune`` module by subclassing the ``BasePruningMethod``
base class, the same way all other pruning methods do. The base class
implements the following methods for you: ``__call__``, ``apply_mask``,
``apply``, ``prune``, and ``remove``. Beyond some special cases, you shouldn't
have to reimplement these methods for your new pruning technique.
You will, however, have to implement ``__init__`` (the constructor),
and ``compute_mask`` (the instructions on how to compute the mask
for the given tensor according to the logic of your pruning
technique). In addition, you will have to specify which type of
pruning this technique implements (supported options are ``global``,
``structured``, and ``unstructured``). This is needed to determine
how to combine masks in the case in which pruning is applied
iteratively. In other words, when pruning a pre-pruned parameter,
the current prunining techique is expected to act on the unpruned
portion of the parameter. Specifying the ``PRUNING_TYPE`` will
enable the ``PruningContainer`` (which handles the iterative
application of pruning masks) to correctly identify the slice of the
parameter to prune.

Let's assume, for example, that you want to implement a pruning
technique that prunes every other entry in a tensor (or -- if the
tensor has previously been pruned -- in the remaining unpruned
portion of the tensor). This will be of ``PRUNING_TYPE='unstructured'``
because it acts on individual connections in a layer and not on entire
units/channels (``'structured'``), or across different parameters
(``'global'``).



In [ ]:
class FooBarPruningMethod(prune.BasePruningMethod):
    """Prune every other entry in a tensor
    """
    PRUNING_TYPE = 'unstructured'

    def compute_mask(self, t, default_mask):
        mask = default_mask.clone()
        mask.view(-1)[::2] = 0 
        return mask

Now, to apply this to a parameter in an ``nn.Module``, you should
also provide a simple function that instantiates the method and
applies it.



In [ ]:
def foobar_unstructured(module, name):
    """Prunes tensor corresponding to parameter called `name` in `module`
    by removing every other entry in the tensors.
    Modifies module in place (and also return the modified module) 
    by:
    1) adding a named buffer called `name+'_mask'` corresponding to the 
    binary mask applied to the parameter `name` by the pruning method.
    The parameter `name` is replaced by its pruned version, while the 
    original (unpruned) parameter is stored in a new parameter named 
    `name+'_orig'`.

    Args:
        module (nn.Module): module containing the tensor to prune
        name (string): parameter name within `module` on which pruning
                will act.

    Returns:
        module (nn.Module): modified (i.e. pruned) version of the input
            module
    
    Examples:
        >>> m = nn.Linear(3, 4)
        >>> foobar_unstructured(m, name='bias')
    """
    FooBarPruningMethod.apply(module, name)
    return module

Let's try it out!



In [ ]:
model = LeNet()
foobar_unstructured(model.fc3, name='bias')

print(model.fc3.bias_mask)